apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: the-movie-db
  description: |
    The Movie Database (TMDB) is a community built movie and TV database. 
    Every piece of data has been added by our amazing community dating back to 2008. 
    TMDB's strong international focus and breadth of data is largely unmatched and something we're incredibly proud of. 
    Put simply, we live and breathe community and that's precisely what makes us different.
  links:
    - title: Website
      url: https://www.themoviedb.org/
    - title: Documentation
      url: https://developer.themoviedb.org/docs
spec:
  type: database
  owner: TiVo Platform Technologies
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: movie-assignment
  title: Movie Assignment
  description: |
    A movie web app that allows users to search, sort, add and view movies.
  links:
    - title: Website
      url: https://movie-assignment-a417e.web.app/
  annotations:
    github.com/project-slug: anshumandubey1/movie-assignment
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: anshumandubey1
  dependsOn:
    - resource:default/the-movie-db